### ISSUE TITLE
Module : Javascript Project: Counter app

### ISSUE THREAD

**Issue by MAYANK816** [Mridul2820/Hacktoberfest#14]
Will redesign the Counter app with new color codes and also fix the bug so it will not go down less than 0.

**Comment by Mridul2820** [comment]
@MAYANK816 sure you can make your own version of the project. Don't modify the old code. Add your project in a different folder with a slightly different name

**Comment by Priya5545** [comment]
Hello please assign this issues.

**Comment by MAYANK816** [comment]
Sir I have reviewed my profile on hacktoberfest but I am getting these issues.

![image](https://user-images.githubusercontent.com/63389169/194132613-b34b6ae9-5863-4a8d-a043-43c90cc8d208.png)

**Comment by Mridul2820** [comment]
Hi @MAYANK816 Hactober Fest team is too much strict this time. I am seeing too many repos got excluded

You can contribute to this https://github.com/Mridul2820/awesome-javascript
